---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mof-backend
spec:
  selector:
    matchLabels:
      app: mof
      service: backend
  template:
    metadata:
      labels:
        app: mof
        service: backend
    spec:
      initContainers:
        - name: init
          image: ghcr.io/map-of-feel/backend.db_migrations:main-04366dc
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mof-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_DB
      containers:
        - name: backend
          image: ghcr.io/map-of-feel/backend:main-04366dc
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mof-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mof-postgres
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: mof-backend
spec:
  selector:
    app: mof
    service: backend
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mof-backend
  namespace: ca-mof
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http
  labels:
    app: mof
    service: backend
spec:
  ingressClassName: nginx
  rules:
    - host: map-of-feel.haus-voller-freunde.de
      http:
        paths:
          - pathType: Prefix
            path: "/api/"
            backend:
              service:
                name: mof-backend
                port:
                  number: 80
  tls:
    - hosts:
        - map-of-feel.haus-voller-freunde.de
      secretName: mof-backend-tls
